"""empty message

Revision ID: 6526fd1464d9
Revises: 
Create Date: 2023-02-13 22:15:51.426299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6526fd1464d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('product_item_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['price'])
        batch_op.create_unique_constraint(None, ['item'])
        batch_op.drop_column('item_name')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_first_name_key', type_='unique')
        batch_op.drop_constraint('user_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('user_first_name_key', ['first_name'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_item_name_key', ['item_name'])
        batch_op.drop_column('item')
        batch_op.drop_column('id')

    op.drop_table('cart')
    # ### end Alembic commands ###
