"""empty message

Revision ID: 7abcb4441fbe
Revises: 3b7091f587fe
Create Date: 2023-02-13 00:46:38.419684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abcb4441fbe'
down_revision = '3b7091f587fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('cart_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('product_item_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['price'])
        batch_op.create_unique_constraint(None, ['item'])
        batch_op.drop_column('item_id')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_first_name_key', type_='unique')
        batch_op.drop_constraint('user_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('user_first_name_key', ['first_name'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_item_name_key', ['item_name'])
        batch_op.drop_column('item')
        batch_op.drop_column('id')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_product_id_fkey', 'product', ['product_id'], ['item_id'])
        batch_op.drop_column('item_id')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
